language: c
# By setting the language to c instead of python, it's possible to use apt-get.
# It's difficult to get the scipy stack installed via pip.

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

virtualenv:
  system_site_packages: true

# We'll install as many packages as possible via pip, but some require apt-get.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update -qq
  - sudo apt-get -q install python-scipy
  - sudo apt-get -q install python-pyside python-qt4
#  - sudo apt-get -q libwxgtk2.8-0 python-wxtools
  - pip install numpy matplotlib pandas control

install:
  - python setup.py build && sudo python setup.py install

script:
  - python runtests.py --raise
